version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: aiogramdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aiogram
      POSTGRES_USER: aidar
      POSTGRES_PASSWORD: aidar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: